### ISSUE TITLE
Add: Write text on Image

### ISSUE THREAD

**Issue by haashemi** [haashemi/painter#1]
# Feature: Text Writer

## Description

We'd like to be able to write some text on our generated images. The API should be simple and flexible.

## Initial Requirements:

- [X] Parsing OpenType fonts using `sfnt.Parse`.
- [X] Creating a `font.Face` from the font using `opentype.NewFace`.
- [X] Basic writing on the image using `font.Drawer`.

## Roadmap:

- [ ] Fallback font support.
- [ ] RTL support.
- [ ] Fit-height support.
- [ ] Fit-width support.
- [ ] Text overflow behaviors.

This roadmap might change at any time. It's also not sorted by priority.

**Comment by haashemi** [comment]
Initial version of the text write could be something like this:

```go
// Preparing the image. it doesn't really matter how.
img := painter.New(690, 420)

// Cur text color could be any image.Image.
textColor := image.NewUniform(color.White)

// Obviously, our text!
text := "Give painter a star <3"

// Parse the font file
font, _ := painter.ParseFont(fontFileBytes)

// Create a new font face from our font
face := font.NewFace(42.0)

// Write our text on the image with color of textColor. from x = 42 and centered vertically.
face.Write(img, textColor, text, 42, (420-face.Height())/2)
```

**Comment by haashemi** [comment]
Implementing a *writer* in *painter* is not a good idea.

The most basic implementation we currently have is fine, but it's something that you don't even have to use an external package; the stdlib package is straight-forward enough.

After some investigation, I've found out that *Writer* comes with a huge amount of its own complexities, which is not the goal of *painter*, which wants to be as simple as possible. The main goal of adding *Writer* was to fully support RTL texts (ligature and shaping stuff) along with additional helpers like *text wrappers* to ease the development of writing text on images.

But it's not as simple as it may sound, and that's why something like [harfbuzz](https://github.com/harfbuzz/harfbuzz) has been made. (thanks to @er-azh for pointing this out to me.)

I'm still planning on implementing this, but somewhere else, at a better time with more knowledge about what I'm doing.
